### ISSUE TITLE
Remove dependency on ngrok

### ISSUE THREAD

**Issue by gergnz** [atlassian/hubot-stride#1]
Can I please understand what the requirement is for ngrok?

**Comment by lukebatchelor** [comment]
I'm not a maintainer here, but ngrok is used to create a tunnel to your local machine for use during local development.

When installing the add-on, stride needs to download your descriptor/post to your service. If it's running on your local machine, and your machine is not exposed to the internet, it wouldn't be able to connect. 

Hope that makes sense

**Comment by gergnz** [comment]
Sure I understand that @lukebatchelor, but I don't see it as a dependency for production. I would suggest that maybe there is a more appropriate way to setup and secure it for production deployments?

**Comment by MarshallOfSound** [comment]
@gergnz Also not a maintainer here, but ngrok should only be used for development.  It is used purely as a tunnel to your local machine during development, if you wanted to run something like this in production you should 100% just host it on a server somewhere, not tunnel it through ngrok 👍 

There isn't an explicit [dependency on ngrok](https://github.com/atlassian/hubot-stride/blob/master/package.json) rather an implicit one in the README which appears to simply explain how to set this repository up for development not for production usage 👍

**Comment by icheremskyi** [comment]
Hi! maintainer here,

In short -- no, you do not need `ngrok` in production (and there is no such dependency in `package.json`)

You need `ngrok` for development, so you are able to run your `hubot` server on `localhost` and broadcast that to the Internet. This way you can get an URL that you can paste into `Stride`'s installation dialog.

In production your app will (probably) be running `hubot` server in the cloud and will have a domain name that you will be able to paste into `Stride`'s installation dialog.

Hope that this cleared things a bit

**Comment by stahnma** [comment]
Is this a limitation of stride, that I have to have hubot exposed to the internet? With hipchat I simply had my hubot connect via the hipchat adapter running inside my firewall.

**Comment by lukebatchelor** [comment]
Were you using a server instance of HC by any chance. Not an expert on the server products, but that's the only way I could see that being possible.

Otherwise HC would not be able to reach your service right?

**Comment by stahnma** [comment]
No. Hipchat didn't have to reach the service. The service reaches hipchat,
reads messages via the api and takes action. It's just a client.

**Comment by balexx** [comment]
So to use hubot with stride we need to punch a hole in the firewall or create a tunnel using ngrok?
