### ISSUE TITLE
How do I format messages?

### ISSUE THREAD

**Issue by stahnma** [atlassian/hubot-stride#5]
I am migrating over from hipchat, and for code I could simply use `/code` in the message to get monospace fonts. With stride, I tried `/code`, just backtickets, four spaces ala markdown, and basically, can't get it to work. Google for stride message format gets me all the standard markdown stuff, but my hubot doesn't seem to use it. It looks like messages are not formatting at all using this adapter?

**Comment by lukebatchelor** [comment]
Hiya, not a maintainer or active user but have worked with the APIs before, hoping this might be useful

Not sure what your googling showed, but my first result for  "Stride Message Format" is
https://developer.atlassian.com/cloud/stride/learning/formatting-messages/

Which talks about the ADF structures used for sending rich messages. 

Depending on what you are doing, I'd recommend either creating the message in a visual editor like this:
https://developer.atlassian.com/cloud/stride/apis/document/playground/

If your messages are static, just use the rendered ADF from there, if it's just small parts changing (structure stays the same) I'd just put that in a template literal. If you need more fine-grained control you'll wanna look at a library like
https://www.npmjs.com/package/adf-builder

Interestingly though, whilst just looking these links up I found this too which might be even easier if you have existing code for generating your markdown (I hadn't seen or used it before but it looks like the key is simply setting the content type)
https://developer.atlassian.com/cloud/stride/learning/sending-messages-as-markdown/

Also, I haven't looked into hubot messages themselves it's possible none of this will be relevant! 👌

**Comment by stahnma** [comment]
I'm aware there are ways to format messages for stride overall. What about
using hubot? Ideally you can format a message with writing stride-specific
code, as that should be in the adapter. Are you suggesting I modify the
adapter? How else would these templates come into play?

**Comment by stahnma** [comment]
In looking at the adapter, it looks like this might be a limitation in stride (which I would consider a serious flaw...enough not to move forward with it as a messaging platform). It looks like there isn't a way for stride to format a message based on content. It has to be told how to format it via ADF which is a json structure, meaning I have to build out huge objects to send formatted strings -- which also means the common abstractions for hubot (e.g. `msg.send`) won't work because I'd have to create new methods for things like formatting. I hope I'm totally off-base here, but in looking through the way `paragraph` object is built, it looks like the adapter is just hard coded to 'text' -- which is fine, unless you ever want formatting. (And I do). 

I'm really hoping I'm missing some here and can do formatting (mostly monospace, but also rendering images inline).

**Comment by MarshallOfSound** [comment]
_not a maintainer here disclaimer_

@stahnma There is a Stride endpoint for sending raw markdown as a Stride message.  See the API docs here https://developer.atlassian.com/cloud/stride/learning/sending-messages-as-markdown/

I'm not super familiar with hubot but from the sounds of it you simply need some kind of switch exposed by this adapter to send a raw markdown message instead of dumping the message into a `paragraph` element in an ADF document.  Does that sound about right?

**Comment by rudzon** [comment]
@stahnma I agree that not being able to format message is an issue. Will fix the it in the next update

**Comment by rudzon** [comment]
@stahnma fixed and published in 1.0.6 version
